# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    default_config: my_config
    configs:
        my_config:
            licenseKey: "TEAVZF826.HGG363BJD076"
            toolbar: full
            language: 'fr'
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
