name: Beaup deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn  openvpn-systemd-resolved        

      - name: Setup VPN config
        run: |
          echo "${{ secrets.OVPN_CA }}" > ca.crt
          echo "${{ secrets.OVPN_CERT }}" > user.crt
          echo "${{ secrets.OVPN_USER_KEY }}" > user.key
          echo "${{ secrets.OVPN_USER_CREDENTIALS }}" > secret.txt
#          echo "${{ secrets.TLS_KEY }}" > tls.key          

      - name: Connect VPN
        run: |
          sudo openvpn --config ".github/workflows/beaup.ovpn" --log "vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: until ping -c1 10.187.20.254; do sleep 2; done
        # OR
        #run: until dig @your-dns-resolver your-server-address A +time=1; do sleep 2; done

      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.FORMATOOL_HOST }}
          username: ${{ secrets.FORMATOOL_SERVER_USERNAME }}
          password: ${{ secrets.FORMATOOL_SERVER_PASSW }}
          script: |
            cd /home/aethril/formatool
            git pull
            
            # composer update
            # sf d:m:m
            # sf c:c
            # sf assets:install

      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn