name: moncampus.net deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MONCAMPUSNET_SSH_HOST }}
          username: ${{ secrets.MONCAMPUSNET_SSH_USER }}
          key: ${{ secrets.MONCAMPUSNET_SSH_KEY }}
          #passphrase: ${{ secrets.MONCAMPUSNET_SSH_PASSPHRASE }}
          script: |
              cd /home/bitnami/htdocs
              sudo su daemon
              ls -al
              