name: moncampus.net deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MONCAMPUSNET_SSH_HOST }}
          username: ${{ secrets.MONCAMPUSNET_SSH_USER }}
          key: ${{ secrets.MONCAMPUSNET_SSH_KEY }}
          #passphrase: ${{ secrets.MONCAMPUSNET_SSH_PASSPHRASE }}
          script: |
              sudo chown -Rf bitnami:bitnami /home/bitnami/htdocs/ 
              cd /home/bitnami/htdocs
              sudo npm install
              sudo chown -Rf daemon:daemon /home/bitnami/htdocs/
              git config --global --add safe.directory ./
              git config --global --add safe.directory /opt/bitnami/apache/htdocs
              git reset --hard
              git pull 
              composer update
              npm run build
              php bin/console d:m:m --no-interaction
              php bin/console c:c
              php bin/console assets:install
              sudo chown -Rf daemon:daemon /home/bitnami/htdocs/